table 'Orders' =
		DATATABLE(
			"Row ID", INTEGER,
			"Order ID", STRING,
			"Order Date", DATETIME,
			"Ship Date", DATETIME,
			"Ship Mode", STRING,
			"Customer ID", STRING,
			"Customer Name", STRING,
			"Segment", STRING,
			"Country", STRING,
			"City", STRING,
			"State", STRING,
			"Postal Code", STRING,
			"Region", STRING,
			"Product ID", STRING,
			"Category", STRING,
			"Sub-Category", STRING,
			"Product Name", STRING,
			"Sales", DOUBLE,
			"Quantity", INTEGER,
			"Discount", DOUBLE,
			"Profit", DOUBLE,
			{
				{1, "US-2022-103800", DATE(2022, 1, 3), DATE(2022, 1, 7), "Standard Class", "DP-13000", "Darren Powers", "Consumer", "United States", "Houston", "Texas", "77095", "Central", "OFF-PA-10000174", "Office Supplies", "Paper", "Message Book, Wirebound, Four 5 1/2"" X 4"" Forms/Pg., 200 Dupl. Sets/Book", 16.45, 2, 0.20, 5.5512},
				{2, "US-2022-112326", DATE(2022, 1, 4), DATE(2022, 1, 8), "Standard Class", "PO-19195", "Phillina Ober", "Home Office", "United States", "Naperville", "Illinois", "60540", "Central", "OFF-BI-10004094", "Office Supplies", "Binders", "GBC Standard Plastic Binding Systems Combs", 3.54, 2, 0.80, -5.4870},
				{3, "US-2022-112326", DATE(2022, 1, 4), DATE(2022, 1, 8), "Standard Class", "PO-19195", "Phillina Ober", "Home Office", "United States", "Naperville", "Illinois", "60540", "Central", "OFF-LA-10003223", "Office Supplies", "Labels", "Avery 508", 11.78, 3, 0.20, 4.2717},
				{4, "US-2022-112326", DATE(2022, 1, 4), DATE(2022, 1, 8), "Standard Class", "PO-19195", "Phillina Ober", "Home Office", "United States", "Naperville", "Illinois", "60540", "Central", "OFF-ST-10002743", "Office Supplies", "Storage", "SAFCO Boltless Steel Shelving", 272.74, 3, 0.20, -64.7748},
				{5, "US-2022-141817", DATE(2022, 1, 5), DATE(2022, 1, 12), "Standard Class", "MB-18085", "Mick Brown", "Consumer", "United States", "Philadelphia", "Pennsylvania", "19143", "East", "OFF-AR-10003478", "Office Supplies", "Art", "Avery Hi-Liter EverBold Pen Style Fluorescent Highlighters, 4/Pack", 19.54, 3, 0.20, 4.8840},
				{6, "US-2022-167199", DATE(2022, 1, 6), DATE(2022, 1, 10), "Standard Class", "ME-17320", "Maria Etezadi", "Home Office", "United States", "Henderson", "Kentucky", "42420", "South", "FUR-CH-10004063", "Furniture", "Chairs", "Global Deluxe High-Back Manager's Chair", 2573.82, 9, 0.00, 746.4078},
				{7, "US-2022-167199", DATE(2022, 1, 6), DATE(2022, 1, 10), "Standard Class", "ME-17320", "Maria Etezadi", "Home Office", "United States", "Henderson", "Kentucky", "42420", "South", "OFF-AR-10001662", "Office Supplies", "Art", "Rogers Handheld Barrel Pencil Sharpener", 5.48, 2, 0.00, 1.4796},
				{8, "US-2022-106054", DATE(2022, 1, 6), DATE(2022, 1, 7), "First Class", "JO-15145", "Jack O'Briant", "Corporate", "United States", "Athens", "Georgia", "30605", "South", "OFF-AR-10002399", "Office Supplies", "Art", "Dixon Prang Watercolor Pencils, 10-Color Set with Brush", 12.78, 3, 0.00, 5.2398},
				{9, "US-2022-167199", DATE(2022, 1, 6), DATE(2022, 1, 10), "Standard Class", "ME-17320", "Maria Etezadi", "Home Office", "United States", "Henderson", "Kentucky", "42420", "South", "OFF-BI-10004632", "Office Supplies", "Binders", "Ibico Hi-Tech Manual Binding System", 609.98, 2, 0.00, 274.4910},
				{10, "US-2022-167199", DATE(2022, 1, 6), DATE(2022, 1, 10), "Standard Class", "ME-17320", "Maria Etezadi", "Home Office", "United States", "Henderson", "Kentucky", "42420", "South", "OFF-FA-10001883", "Office Supplies", "Fasteners", "Alliance Super-Size Bands, Assorted Sizes", 31.12, 4, 0.00, 0.3112},
				{11, "US-2022-167199", DATE(2022, 1, 6), DATE(2022, 1, 10), "Standard Class", "ME-17320", "Maria Etezadi", "Home Office", "United States", "Henderson", "Kentucky", "42420", "South", "OFF-PA-10000955", "Office Supplies", "Paper", "Southworth 25% Cotton Granite Paper & Envelopes", 6.54, 1, 0.00, 3.0084},
				{12, "US-2022-130813", DATE(2022, 1, 6), DATE(2022, 1, 8), "Second Class", "LS-17230", "Lycoris Saunders", "Consumer", "United States", "Los Angeles", "California", "90049", "West", "OFF-PA-10002005", "Office Supplies", "Paper", "Xerox 225", 19.44, 3, 0.00, 9.3312},
				{13, "US-2022-167199", DATE(2022, 1, 6), DATE(2022, 1, 10), "Standard Class", "ME-17320", "Maria Etezadi", "Home Office", "United States", "Henderson", "Kentucky", "42420", "South", "TEC-PH-10004539", "Technology", "Phones", "Wireless Extenders zBoost YX545 SOHO Signal Booster", 755.96, 4, 0.00, 204.1092},
				{14, "US-2022-167199", DATE(2022, 1, 6), DATE(2022, 1, 10), "Standard Class", "ME-17320", "Maria Etezadi", "Home Office", "United States", "Henderson", "Kentucky", "42420", "South", "TEC-PH-10004977", "Technology", "Phones", "GE 30524EE4", 391.98, 2, 0.00, 113.6742},
				{15, "US-2022-105417", DATE(2022, 1, 7), DATE(2022, 1, 12), "Standard Class", "VS-21820", "Vivek Sundaresam", "Consumer", "United States", "Huntsville", "Texas", "77340", "Central", "FUR-FU-10004864", "Furniture", "Furnishings", "Howard Miller 14-1/2"" Diameter Chrome Round Wall Clock", 76.73, 3, 0.60, -53.7096},
				{16, "US-2022-105417", DATE(2022, 1, 7), DATE(2022, 1, 12), "Standard Class", "VS-21820", "Vivek Sundaresam", "Consumer", "United States", "Huntsville", "Texas", "77340", "Central", "OFF-BI-10003708", "Office Supplies", "Binders", "Acco Four Pocket Poly Ring Binder with Label Holder, Smoke, 1""", 10.43, 7, 0.80, -18.2525},
				{17, "US-2022-135405", DATE(2022, 1, 9), DATE(2022, 1, 13), "Standard Class", "MS-17830", "Melanie Seite", "Consumer", "United States", "Laredo", "Texas", "78041", "Central", "OFF-AR-10004078", "Office Supplies", "Art", "Newell 312", 9.34, 2, 0.20, 1.1680},
				{18, "US-2022-135405", DATE(2022, 1, 9), DATE(2022, 1, 13), "Standard Class", "MS-17830", "Melanie Seite", "Consumer", "United States", "Laredo", "Texas", "78041", "Central", "TEC-AC-10001266", "Technology", "Accessories", "Memorex Micro Travel Drive 8 GB", 31.20, 3, 0.20, 9.7500},
				{19, "US-2022-149020", DATE(2022, 1, 10), DATE(2022, 1, 15), "Standard Class", "AJ-10780", "Anthony Jacobs", "Corporate", "United States", "Springfield", "Virginia", "22153", "South", "FUR-FU-10000965", "Furniture", "Furnishings", "Howard Miller 11-1/2"" Diameter Ridgewood Wall Clock", 51.94, 1, 0.00, 21.2954},
				{20, "US-2022-149020", DATE(2022, 1, 10), DATE(2022, 1, 15), "Standard Class", "AJ-10780", "Anthony Jacobs", "Corporate", "United States", "Springfield", "Virginia", "22153", "South", "OFF-LA-10004272", "Office Supplies", "Labels", "Avery 482", 2.89, 1, 0.00, 1.3583},
				{21, "US-2022-130092", DATE(2022, 1, 11), DATE(2022, 1, 14), "First Class", "SV-20365", "Seth Vernon", "Consumer", "United States", "Dover", "Delaware", "19901", "East", "FUR-FU-10000010", "Furniture", "Furnishings", "DAX Value U-Channel Document Frames, Easel Back", 9.94, 2, 0.00, 3.0814},
				{22, "US-2022-157147", DATE(2022, 1, 13), DATE(2022, 1, 18), "Standard Class", "BD-11605", "Brian Dahlen", "Consumer", "United States", "San Francisco", "California", "94109", "West", "FUR-BO-10003034", "Furniture", "Bookcases", "O'Sullivan Elevations Bookcase, Cherry Finish", 334.00, 3, 0.15, 3.9294},
				{23, "US-2022-109232", DATE(2022, 1, 13), DATE(2022, 1, 16), "Second Class", "ND-18370", "Natalie DeCherney", "Consumer", "United States", "Mount Pleasant", "South Carolina", "29464", "South", "FUR-CH-10000422", "Furniture", "Chairs", "Global Highback Leather Tilter in Burgundy", 545.94, 6, 0.00, 87.3504},
				{24, "US-2022-157147", DATE(2022, 1, 13), DATE(2022, 1, 18), "Standard Class", "BD-11605", "Brian Dahlen", "Consumer", "United States", "San Francisco", "California", "94109", "West", "OFF-AR-10003514", "Office Supplies", "Art", "4009 Highlighters by Sanford", 19.90, 5, 0.00, 6.5670},
				{25, "US-2022-118192", DATE(2022, 1, 13), DATE(2022, 1, 18), "Standard Class", "MM-17920", "Michael Moore", "Consumer", "United States", "Newark", "Ohio", "43055", "East", "OFF-BI-10003476", "Office Supplies", "Binders", "Avery Metallic Poly Binders", 3.44, 2, 0.70, -2.5212},
				{26, "US-2022-162775", DATE(2022, 1, 13), DATE(2022, 1, 15), "Second Class", "CS-12250", "Chris Selesnick", "Corporate", "United States", "Bossier City", "Louisiana", "71111", "South", "OFF-BI-10004187", "Office Supplies", "Binders", "3-ring staple pack", 5.64, 3, 0.00, 2.7072},
				{27, "US-2022-162775", DATE(2022, 1, 13), DATE(2022, 1, 15), "Second Class", "CS-12250", "Chris Selesnick", "Corporate", "United States", "Bossier City", "Louisiana", "71111", "South", "OFF-EN-10001532", "Office Supplies", "Envelopes", "Brown Kraft Recycled Envelopes", 50.94, 3, 0.00, 25.4700},
				{28, "US-2022-162775", DATE(2022, 1, 13), DATE(2022, 1, 15), "Second Class", "CS-12250", "Chris Selesnick", "Corporate", "United States", "Bossier City", "Louisiana", "71111", "South", "OFF-EN-10001990", "Office Supplies", "Envelopes", "Staple envelope", 11.36, 2, 0.00, 5.3392},
				{29, "US-2022-118192", DATE(2022, 1, 13), DATE(2022, 1, 18), "Standard Class", "MM-17920", "Michael Moore", "Consumer", "United States", "Newark", "Ohio", "43055", "East", "OFF-PA-10002947", "Office Supplies", "Paper", "Xerox 1923", 37.41, 7, 0.20, 13.0928},
				{30, "US-2022-162775", DATE(2022, 1, 13), DATE(2022, 1, 15), "Second Class", "CS-12250", "Chris Selesnick", "Corporate", "United States", "Bossier City", "Louisiana", "71111", "South", "OFF-ST-10000025", "Office Supplies", "Storage", "Fellowes Stor/Drawer Steel Plus Storage Drawers", 572.58, 6, 0.00, 34.3548}
			}
		)
	lineageTag: 347ced9d-ccac-4128-bece-1838f3aa3cdb

	column 'Row ID'
		dataType: int64
		lineageTag: 5f95389f-8610-4f1b-b64d-2bae202304e6
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: c8f166a4-19cb-4931-aa4b-c0178fbd9e5a
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		lineageTag: 7b6d29a7-4c5f-4033-8272-5000132d715f
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		lineageTag: e810c255-574e-4cec-a41c-8406d5ba14cc
		summarizeBy: none
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

	column 'Ship Mode'
		dataType: string
		lineageTag: 1b7bf313-f45f-4a40-80ce-23173600b182
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 55773053-e0df-4c3b-857f-f798de35ba3d
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: da0863b0-a0c5-44d6-bc59-15457f48e8d5
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Segment'
		dataType: string
		lineageTag: 1bc55802-2873-462e-a566-ed8f04505bcb
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Country'
		dataType: string
		lineageTag: 2ea791f9-08f6-467f-a1a1-d683d758231f
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'City'
		dataType: string
		lineageTag: c8d645e6-cd51-4e2c-8318-65db6cc74f5c
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'State'
		dataType: string
		lineageTag: 5e1046ff-85f1-435b-91d4-66396b1607fc
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: d58f3970-8e5b-4cbb-8224-dfe2a1d456a6
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column 'Region'
		dataType: string
		lineageTag: a0e8b7f1-6f6a-42f1-949e-fb81b80e484f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 18bd29a9-669c-4a77-8b3a-b9ea0d6ccf47
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Category'
		dataType: string
		lineageTag: 85ed5352-cca6-4f16-8d26-42807bef4198
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Sub-Category'
		dataType: string
		lineageTag: 1a024975-8fb3-4276-bd76-df4d730ba107
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 0dcaa264-cf07-4209-bd46-26bbedaadd65
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Sales'
		dataType: double
		lineageTag: 901ed7a6-2e7a-4964-9f84-669164bab562
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	column 'Quantity'
		dataType: int64
		lineageTag: 70f4322a-0e14-4126-994f-5400454df232
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Discount'
		dataType: double
		lineageTag: 0e35e86b-b1cf-408f-9354-75964971aff7
		summarizeBy: none
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column 'Profit'
		dataType: double
		lineageTag: e74fbcaf-6c1d-485e-a916-bb6fa6cee6d6
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	measure 'Total Sales' = SUM('Orders'[Sales])
		lineageTag: 44c6e5fe-d373-4eb3-b36b-3673c46585a8
		formatString: "$#,##0.00"

	measure 'Total Profit' = SUM('Orders'[Profit])
		lineageTag: 0a79aad5-f03e-4062-8888-3f5156b13085
		formatString: "$#,##0.00"

	measure 'Total Quantity' = SUM('Orders'[Quantity])
		lineageTag: fe0d6898-d248-4559-9d6c-bd1c93c2dbc5
		formatString: "#,##0"

	measure 'Profit Ratio' = DIVIDE(SUM('Orders'[Profit]), SUM('Orders'[Sales]), 0)
		lineageTag: a49ad2c0-acde-46b7-864b-43addd23eb65
		formatString: "0.00%"

	measure 'Avg Discount' = AVERAGE('Orders'[Discount])
		lineageTag: a7114ff9-f591-442f-aff9-e0a52c57360d
		formatString: "0.00%"

	measure 'Order Count' = DISTINCTCOUNT('Orders'[Order ID])
		lineageTag: 5c717853-f9e0-40a1-82c7-1170859e7a83
		formatString: "#,##0"

	annotation PBI_NavigationStepName = Source
	annotation PBI_ResultType = Table
