table 'Default'
	lineageTag: 7a1920d6-1156-abc0-5a60-135aefe8bc67

	column 'Order_Date'
		dataType: dateTime
		lineageTag: 6a688dad-b3d3-12f9-54e6-35c20bced26a
		summarizeBy: none
		sourceColumn: Order_Date

		annotation SummarizationSetBy = Automatic

	column 'Order_ID'
		dataType: string
		lineageTag: 77dedc89-0a83-bc0a-c547-3172bff7c0c5
		summarizeBy: none
		sourceColumn: Order_ID

		annotation SummarizationSetBy = Automatic

	column 'Product_Name'
		dataType: string
		lineageTag: 7e9ad598-d029-1c82-f8b1-3d97ac545e7f
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column 'Category'
		dataType: string
		lineageTag: 19160ffd-fb82-3120-6acd-1488e9681900
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Region'
		dataType: string
		lineageTag: b004ed09-ca06-eecd-c5b9-2321c153083d
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Quantity'
		dataType: int64
		lineageTag: 0855160c-5742-2a8f-8045-8a69cfb929a7
		summarizeBy: none
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column 'Profit'
		dataType: double
		lineageTag: c519bc3d-3b9c-5ad9-ec3d-9e854164e9f3
		summarizeBy: none
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Customer_Name'
		dataType: string
		lineageTag: 7d7bb77a-6313-f934-1137-ac2235fda6f8
		summarizeBy: none
		sourceColumn: Customer_Name

		annotation SummarizationSetBy = Automatic

	column 'Sales'
		dataType: double
		lineageTag: 6a1af86d-9886-0cf8-1147-6254d83462d9
		summarizeBy: none
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

	measure 'Calculation_TotalSales' = SUM('Default'[Sales])
		lineageTag: 2de615e0-1802-0496-8387-9bad087b5582

	measure 'Calculation_TotalProfit' = SUM('Default'[Profit])
		lineageTag: 9da475c8-3e71-4b78-e768-e4786b3b3754

	measure 'Calculation_ProfitRatio' = SUM('Default'[Profit]) / SUM('Default'[Sales])
		lineageTag: ff68ad13-1c10-3b0a-c059-aff62b2c0ff2

	measure 'Calculation_AvgOrderValue' = AVERAGE('Default'[Sales])
		lineageTag: a1ffc262-ccf2-bbf0-cab4-a1bb385cf6c4

	measure 'Calculation_OrderCount' = DISTINCTCOUNT('Default'[Order_ID])
		lineageTag: 93a762d4-8e80-46e9-6d7d-cbdb31adf3a6

	partition 'Default' = m
		mode: import
		source =
				let Source = #table({{"Order_Date", type datetime}, {"Order_ID", type text}, {"Product_Name", type text}, {"Category", type text}, {"Region", type text}, {"Quantity", Int64.Type}, {"Profit", type number}, {"Customer_Name", type text}, {"Sales", type number}}, {{#datetime(2024, 1, 15, 0, 0, 0), "ORD-001", "Laptop", "Technology", "East", 10, 300.1, "John Smith", 1500.5}, {#datetime(2024, 2, 20, 0, 0, 0), "ORD-002", "Desk Chair", "Furniture", "West", 25, 450.25, "Jane Doe", 2300.75}, {#datetime(2024, 3, 10, 0, 0, 0), "ORD-003", "Printer Paper", "Office Supplies", "Central", 5, 120.5, "Bob Johnson", 890.25}, {#datetime(2024, 4, 5, 0, 0, 0), "ORD-004", "Monitor", "Electronics", "South", 15, 240.0, "Alice Brown", 1200.0}, {#datetime(2024, 5, 25, 0, 0, 0), "ORD-005", "Coffee Maker", "Appliances", "North", 30, 680.2, "Charlie Wilson", 3400.99}}) in Source

	annotation PBI_NavigationStepName = Source
	annotation PBI_ResultType = Table
